name: Automated Development Workflow
version: 1.0.0
description: Comprehensive workflow automation with hooks

workflows:
  - id: code-review
    name: Automated Code Review
    triggers:
      - type: git
        events: [commit, push]
      - type: manual
        command: review
    steps:
      - name: Analyze Code
        agent: code-analyzer
        parallel: true
        actions:
          - lint
          - security-scan
          - complexity-check
      - name: Run Tests
        agent: test-runner
        parallel: true
        actions:
          - unit-tests
          - integration-tests
      - name: Generate Report
        agent: doc-generator
        actions:
          - create-review-report

  - id: continuous-integration
    name: CI Pipeline
    triggers:
      - type: git
        events: [push]
        branches: [main, develop]
    steps:
      - name: Build
        command: npm run build
        timeout: 300000
      - name: Test
        parallel: true
        commands:
          - npm run test:unit
          - npm run test:integration
          - npm run test:e2e
      - name: Quality Gates
        parallel: true
        commands:
          - npm run lint
          - npm run type-check
          - npm run security-audit
      - name: Deploy Preview
        condition: branch == 'develop'
        command: npm run deploy:preview

  - id: release-automation
    name: Release Pipeline
    triggers:
      - type: git
        events: [tag]
        pattern: v*
    steps:
      - name: Validate Version
        script: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "Releasing version: $VERSION"
      - name: Build Production
        command: npm run build:production
      - name: Run Full Test Suite
        parallel: false
        commands:
          - npm run test:all
          - npm run test:performance
      - name: Generate Changelog
        agent: doc-generator
        actions:
          - generate-changelog
      - name: Create Release
        command: gh release create
      - name: Deploy Production
        command: npm run deploy:production
        approval: required

  - id: dependency-update
    name: Dependency Management
    triggers:
      - type: schedule
        cron: "0 0 * * MON"
    steps:
      - name: Check Updates
        command: npm outdated
      - name: Update Dependencies
        command: npm update
      - name: Run Tests
        command: npm test
      - name: Create PR
        condition: changes_detected
        command: gh pr create --title "chore: update dependencies"

  - id: performance-monitoring
    name: Performance Analysis
    triggers:
      - type: schedule
        cron: "0 */6 * * *"
      - type: manual
        command: perf
    steps:
      - name: Profile Application
        agent: optimizer
        actions:
          - memory-profile
          - cpu-profile
          - network-analysis
      - name: Analyze Results
        agent: architect
        actions:
          - identify-bottlenecks
          - suggest-optimizations
      - name: Generate Report
        output: .claude/reports/performance.md

  - id: documentation-sync
    name: Documentation Update
    triggers:
      - type: file
        paths:
          - "src/**/*.ts"
          - "src/**/*.js"
        events: [modify]
    steps:
      - name: Extract JSDoc
        command: npm run docs:extract
      - name: Update API Docs
        agent: doc-generator
        actions:
          - update-api-docs
      - name: Sync to Wiki
        condition: branch == 'main'
        command: npm run docs:sync

hooks:
  global:
    pre-workflow:
      - name: Environment Check
        script: |
          echo "Checking environment..."
          node -v
          npm -v
      - name: Load Context
        agent: context7
        action: load-project-context
    
    post-workflow:
      - name: Save State
        agent: sqlite-memory
        action: persist-workflow-state
      - name: Send Notifications
        condition: workflow.status != 'success'
        command: npm run notify:failure
    
    on-error:
      - name: Capture Error Context
        agent: context7
        action: capture-error-context
      - name: Create Issue
        condition: error.severity == 'critical'
        command: gh issue create --title "Workflow Error: ${error.message}"

  workflow-specific:
    code-review:
      pre:
        - name: Fetch Latest
          command: git fetch origin
      post:
        - name: Update PR Status
          condition: trigger.type == 'git' && trigger.event == 'push'
          command: gh pr comment --body "Review completed: ${workflow.result}"
    
    release-automation:
      pre:
        - name: Backup Current
          command: npm run backup:production
      post:
        - name: Notify Team
          command: npm run notify:release

conditions:
  changes_detected: git diff --exit-code
  branch: git rev-parse --abbrev-ref HEAD
  error.severity: ${error.level} >= 3
  workflow.status: ${workflow.exitCode} == 0
  trigger.type: ${trigger.__type}
  trigger.event: ${trigger.__event}

notifications:
  channels:
    - type: webhook
      url: ${WEBHOOK_URL}
      events: [failure, success]
    - type: email
      to: ${TEAM_EMAIL}
      events: [failure]
    - type: github
      events: [all]

configuration:
  parallel_execution: true
  max_concurrent_workflows: 5
  retry_on_failure: true
  max_retries: 3
  timeout_default: 600000
  log_level: info
  artifact_retention_days: 30