# Prometheus設定ファイル
# Personal Cooking Recipe監視設定

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'recipe-monitor'

# Rule files
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # Prometheus自身の監視
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Node Exporter（システムメトリクス）
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Frontend（Next.js）監視
  - job_name: 'frontend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['frontend:3000']
    scrape_interval: 30s

  # Backend（Node.js）監視
  - job_name: 'backend'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['backend:5000']
    scrape_interval: 30s

  # API（FastAPI）監視
  - job_name: 'api'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 30s

  # Nginx監視
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 30s

  # Database監視（SQLite metrics via custom exporter）
  - job_name: 'database'
    static_configs:
      - targets: ['db-exporter:9104']
    scrape_interval: 60s

# Alertmanager設定
alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']